"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['app.py']
DATA_FILES = []
OPTIONS = {
    'argv_emulation': False,  # We already disabled this to avoid Carbon issues.
    'packages': ['cv2', 'mediapipe', 'speech_recognition', 'pyttsx3',
                 'pyautogui', 'rubicon', 'pyaudio'],  # Notice only 'rubicon' here.
    'includes': ['rubicon', 'pyaudio'],  # Include 'rubicon' and 'pyaudio' here.
    
}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)