name: CI Pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest  # or macos-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Clear Pip Cache
        run: pip cache purge

      - name: Upgrade Pip & Build Tools
        run: pip install --upgrade pip setuptools wheel build

      - name: Install Dependencies
        run: pip install --no-cache-dir -r requirements.txt

      - name: Install Problematic Packages Separately
        run: |
          pip install --no-cache-dir definitions || echo "Failed to install definitions"
          pip install --no-cache-dir sets || echo "Failed to install sets"

      # - name: Run Tests
      #   run: pytest tests/
