name: Test App Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-app:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install py2app

      - name: Build the app with py2app
        run: |
          # Clean previous builds if any
          rm -rf build dist
          python setup.py py2app

      - name: Launch and test the app
        run: |
          # Launch the app in the background
          ./dist/app.app/Contents/MacOS/app &
          APP_PID=$!
          echo "Launched app with PID ${APP_PID}"
          # Wait a few seconds for the app to start up
          sleep 10
          # Check if the app is running; exit with error if not
          if ps -p $APP_PID > /dev/null; then
            echo "App is running successfully."
            kill $APP_PID
          else
            echo "App did not start successfully."
            exit 1
          fi
